### ISSUE TITLE
Tracker: Stops recording harvests on session change

### ISSUE THREAD

**Issue by dj-riley** [LordHansCapon/cotw-harvest-tracker#10]
The tracker will not record any additional harvests after a session change due to a new session score address that is not being utilized. This can occur whenever going from single player onto a multiplayer server, changing multiplayer servers, or changing from multiplayer back to single player. In these instances, the `session_score_address` changes, but `harvest_base_address`, `fur_type_base_address`, and `fur_type_base_address_2` do not change.

**Comment by dj-riley** [comment]
Proposed PR solution to issue: #11

**Comment by LordHansCapon** [comment]
Probably the cause for #2

**Comment by dj-riley** [comment]
> Probably the cause for #2

I'm blind🤦My apologies, should have read through all other issues before opening a duplicate.
