### ISSUE TITLE
Enhancement (Tracker): Optionally launch game on init, if not already open

### ISSUE THREAD

**Issue by dj-riley** [LordHansCapon/cotw-harvest-tracker#12]
**Enhancement request**:

On the tracker's initialization, if CotW isn't already running, the tracker app should prompt the user if they would like to launch the game instead of automatically quitting the tracker. This will therefore eliminate the need to manually rerun the tracker app if you forget to first launch the game.

- If answering `y`, the tracker app will launch CotW via Steam and the tracker app will continue initializing & obtain all necessary addresses for harvesting after game has initialized.
- If answering `n`, the tracker app will quit as normal without error, game is not launched.

**Comment by LordHansCapon** [comment]
Tracker should not have this responsibility.
