### ISSUE TITLE
name 'exit' is not defined

### ISSUE THREAD

**Issue by xptical** [LordHansCapon/cotw-harvest-tracker#7]
Console window returns this.  I don't know if it's new or not...

`Would you like to record your latest kill which happened before starting this program? y/n: n
Latest kill was not recorded.
- All is good, we are checking your harvest every second -
[1] WHITETAIL DEER - [2023/12/04 12:03:17] | Weight: 40.0 | Fur: RED BROWN | Gender: 2 | Score: 150 | Rating: 0.0 | Cash: 458 | XP: 79 | RatingIcon: 4 | Difficulty: 0.0
 > Failed to read process memory. Have you closed the game? <
Press Enter to close...
Exception!
name 'exit' is not defined
 > Failed to read process memory. Have you closed the game? <
Press Enter to close...`

**Comment by LordHansCapon** [comment]
Is it after you have closed the game? If so, then ye, its been around. But since it does not affect runtime, you can close the commandline window and thats it. No harm done.

**Comment by xptical** [comment]
Gotcha.
