### ISSUE TITLE
Harvests.sav with corrupted entries bug

### ISSUE THREAD

**Issue by poyepolomi** [LordHansCapon/cotw-harvest-tracker#8]
[harvests.zip](https://github.com/LordHansCapon/cotw-harvest-tracker/files/13626817/harvests.zip)

**Comment by LordHansCapon** [comment]
Thank you!

A new release has been put out to address the viewer crash. It should display UNKNOWN where the corrupted gender data should be.

You can download the latest release here:
https://github.com/LordHansCapon/cotw-harvest-tracker/releases/tag/1.16
