### ISSUE TITLE
Currupt harvest.sav

### ISSUE THREAD

**Issue by S0mR** [LordHansCapon/cotw-harvest-tracker#9]
Hi LordHansCapon,

thank you for this tool. Something like this has been missing from the game so far.

However, I have a problem with harvest.sav. I suspect that it is related to the fact that I am using a German OS.

I have already switched the game to English and can also see the correctly recognized animal in the tracker. 

In the viewer I also see an entry for the map and for the animal, but as soon as I want to look at the harvest I only see a "500 Server error" KeyError:770

![image](https://github.com/LordHansCapon/cotw-harvest-tracker/assets/11887690/2991f553-62df-4e02-ab0e-ab81da9617e2)

[harvests.zip](https://github.com/LordHansCapon/cotw-harvest-tracker/files/13705392/harvests.zip)

![image](https://github.com/LordHansCapon/cotw-harvest-tracker/assets/11887690/57c162d8-a9ab-4718-bf4b-0164e592f658)

**Comment by LordHansCapon** [comment]
Hi there!

Could you please attach your harvests.sav file so I can take a look? :)

**Comment by S0mR** [comment]
i already did 
its between the two screenshots

**Comment by LordHansCapon** [comment]
A new release has been issued to fix the issue.

Get it here:
https://github.com/LordHansCapon/cotw-harvest-tracker/releases/tag/1.17
